### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Sameetdmr** [Sameetdmr/Breaking_News#7]
- [x] Yukarıdaki iconlar düzeltilecek.
- [x] Ülke değişimi yukarı taşınacak
- [x] Dil değişimi olunca yukarıdaki kategori isimleri değişecek.
- [x] Componentler düzenlenecek
- [x] Ayrıştırma yapılacak.
- [x] Renk ayarlaması yapılacak
- [x] Todo'lar düzenlenecek
